apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk071-myfirst-api-server
  namespace: class-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk071-myfirst-api-server
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/actuator/prometheus'
        update: cd9a8263
      labels:
        app: sk071-myfirst-api-server
    spec:
      serviceAccountName: default
      containers:
      - name: myfirst-api-server
        image: amdp-registry.skala-ai.com/skala25a/sk071-myfirst-api-server:1.0.0-5-a88ad247
        imagePullPolicy: Always
        env:
        - name: USER_NAME
          value: sk071
        - name: NAMESPACE
          value: class-3
        - name: SPRING_PROFILES_ACTIVE  
          value: "prod"  
